# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/fc_agent',
                'doc_host': 'https://fevzikilas.github.io',
                'git_url': 'https://github.com/fevzikilas/fc_agent',
                'lib_path': 'fc_agent'},
  'syms': {'fc_agent.core': {'fc_agent.core.foo': ('core.html#foo', 'fc_agent/core.py')}}}
